export const POKEMON_LIST_LOADED = 'POKEMON_LIST_LOADED';
export const POKEMON_LIST_CLEARED = 'POKEMON_LIST_CLEARED';
export const POKEMON_LOADED = 'POKEMON_LOADED';
export const CAUGHT_POKEMONS_LIST_LOADED = 'CAUGHT_POKEMONS_LIST_LOADED';